/* OkapiGreen Tracker — prototype sample data
   Placeholder data only. Not real trainee records. */

const COHORTS = [
  { id: "c12", label: "Cohort 12", startDate: "2023-09-04" },
  { id: "c13", label: "Cohort 13", startDate: "2024-02-12" },
  { id: "c14", label: "Cohort 14", startDate: "2024-08-19" },
];

const PROGRAMS = [
  "Solar PV Installation & Maintenance",
  "Solar Design & Engineering",
  "Solar Business & Entrepreneurship",
];

const INDUSTRIES = [
  "Renewable Energy",
  "Utilities",
  "Construction",
  "Retail / Trade",
  "Other",
];

const CONTRACT_TYPES = ["Full-time", "Part-time", "Contract", "Self-employed", "Apprenticeship"];

let TRAINEES = [
  {
    id: "OG-2024-001",
    name: "Nyibol Deng Akol",
    email: "nyibol.deng@example.com",
    phone: "+254 701 223 344",
    linkedin: "linkedin.com/in/nyibol-deng-akol",
    cohortId: "c12",
    program: "Solar PV Installation & Maintenance",
    gradDateActual: "2024-01-26",
    gradDateExpected: "2024-01-26",
    gender: "Female",
    age: 24,
    locationType: "Rural",
    refugeeStatus: "Refugee (South Sudan)",
    disability: "None reported",
    employment: {
      status: "Employed",
      employer: "SolarNow Kenya",
      industry: "Renewable Energy",
      contractType: "Full-time",
      location: "Kakuma, Turkana County",
      dateUpdated: "2026-06-24",
    },
    completeness: 100,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-20",
  },
  {
    id: "OG-2024-002",
    name: "Ismail Abdi Noor",
    email: "ismail.abdi@example.com",
    phone: "+254 702 556 781",
    linkedin: "",
    cohortId: "c12",
    program: "Solar PV Installation & Maintenance",
    gradDateActual: "2024-01-26",
    gradDateExpected: "2024-01-26",
    gender: "Male",
    age: 27,
    locationType: "Rural",
    refugeeStatus: "Refugee (Somalia)",
    disability: "None reported",
    employment: {
      status: "Seeking",
      employer: "",
      industry: "",
      contractType: "",
      location: "Kakuma Camp 3, Turkana County",
      dateUpdated: "2026-05-02",
    },
    completeness: 70,
    surveyStatus: "Pending",
    surveySubmitted: "",
  },
  {
    id: "OG-2024-003",
    name: "Chantal Uwimana",
    email: "chantal.uwimana@example.com",
    phone: "+254 703 118 902",
    linkedin: "linkedin.com/in/chantal-uwimana",
    cohortId: "c12",
    program: "Solar Business & Entrepreneurship",
    gradDateActual: "2024-01-26",
    gradDateExpected: "2024-01-26",
    gender: "Female",
    age: 31,
    locationType: "Rural",
    refugeeStatus: "Refugee (Burundi)",
    disability: "Physical disability (mobility)",
    employment: {
      status: "Employed",
      employer: "Chantal Solar Solutions (self-employed)",
      industry: "Renewable Energy",
      contractType: "Self-employed",
      location: "Kalobeyei Settlement, Turkana County",
      dateUpdated: "2026-06-11",
    },
    completeness: 90,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-09",
  },
  {
    id: "OG-2024-004",
    name: "Peter Lokale Emmanuel",
    email: "",
    phone: "+254 704 887 213",
    linkedin: "",
    cohortId: "c13",
    program: "Solar Design & Engineering",
    gradDateActual: "",
    gradDateExpected: "2026-08-15",
    gender: "Male",
    age: 22,
    locationType: "Rural",
    refugeeStatus: "Host community (Turkana)",
    disability: "None reported",
    employment: {
      status: "Unknown",
      employer: "",
      industry: "",
      contractType: "",
      location: "",
      dateUpdated: "2026-02-14",
    },
    completeness: 40,
    surveyStatus: "Not sent",
    surveySubmitted: "",
  },
  {
    id: "OG-2024-005",
    name: "Amina Hassan Yusuf",
    email: "amina.hassan@example.com",
    phone: "+254 705 340 771",
    linkedin: "linkedin.com/in/amina-hassan-yusuf",
    cohortId: "c13",
    program: "Solar PV Installation & Maintenance",
    gradDateActual: "2026-07-01",
    gradDateExpected: "2026-07-01",
    gender: "Female",
    age: 26,
    locationType: "Rural",
    refugeeStatus: "Refugee (Somalia)",
    disability: "None reported",
    employment: {
      status: "Employed",
      employer: "Renewvia Energy",
      industry: "Renewable Energy",
      contractType: "Contract",
      location: "Kakuma Camp 1, Turkana County",
      dateUpdated: "2026-06-29",
    },
    completeness: 100,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-27",
  },
  {
    id: "OG-2024-006",
    name: "Jean-Claude Mugisha",
    email: "jc.mugisha@example.com",
    phone: "+254 706 902 456",
    linkedin: "linkedin.com/in/jean-claude-mugisha",
    cohortId: "c13",
    program: "Solar Design & Engineering",
    gradDateActual: "2026-07-01",
    gradDateExpected: "2026-07-01",
    gender: "Male",
    age: 29,
    locationType: "Rural",
    refugeeStatus: "Refugee (DR Congo)",
    disability: "None reported",
    employment: {
      status: "Employed",
      employer: "Kenya Power (subcontract)",
      industry: "Utilities",
      contractType: "Part-time",
      location: "Kalobeyei Settlement, Turkana County",
      dateUpdated: "2026-06-15",
    },
    completeness: 85,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-14",
  },
  {
    id: "OG-2024-007",
    name: "Grace Nyandeng Malual",
    email: "grace.nyandeng@example.com",
    phone: "+254 707 664 118",
    linkedin: "",
    cohortId: "c14",
    program: "Solar Business & Entrepreneurship",
    gradDateActual: "",
    gradDateExpected: "2026-12-05",
    gender: "Female",
    age: 23,
    locationType: "Rural",
    refugeeStatus: "Refugee (South Sudan)",
    disability: "None reported",
    employment: {
      status: "Seeking",
      employer: "",
      industry: "",
      contractType: "",
      location: "Kakuma Camp 4, Turkana County",
      dateUpdated: "2026-06-01",
    },
    completeness: 60,
    surveyStatus: "Pending",
    surveySubmitted: "",
  },
  {
    id: "OG-2024-008",
    name: "Mohamed Abdullahi Farah",
    email: "",
    phone: "+254 708 213 990",
    linkedin: "",
    cohortId: "c14",
    program: "Solar PV Installation & Maintenance",
    gradDateActual: "",
    gradDateExpected: "2026-12-05",
    gender: "Male",
    age: 25,
    locationType: "Rural",
    refugeeStatus: "Refugee (Somalia)",
    disability: "Visual impairment (partial)",
    employment: {
      status: "Unknown",
      employer: "",
      industry: "",
      contractType: "",
      location: "",
      dateUpdated: "2026-01-20",
    },
    completeness: 30,
    surveyStatus: "Not sent",
    surveySubmitted: "",
  },
  {
    id: "OG-2024-009",
    name: "Sarah Achieng Otieno",
    email: "sarah.achieng@example.com",
    phone: "+254 709 447 002",
    linkedin: "linkedin.com/in/sarah-achieng-otieno",
    cohortId: "c14",
    program: "Solar PV Installation & Maintenance",
    gradDateActual: "2026-12-05",
    gradDateExpected: "2026-12-05",
    gender: "Female",
    age: 28,
    locationType: "Urban",
    refugeeStatus: "Kenyan national",
    disability: "None reported",
    employment: {
      status: "Employed",
      employer: "M-KOPA Solar",
      industry: "Renewable Energy",
      contractType: "Full-time",
      location: "Nairobi",
      dateUpdated: "2026-06-29",
    },
    completeness: 100,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-28",
  },
  {
    id: "OG-2024-010",
    name: "David Kiptoo Rono",
    email: "david.kiptoo@example.com",
    phone: "+254 710 335 667",
    linkedin: "linkedin.com/in/david-kiptoo-rono",
    cohortId: "c14",
    program: "Solar Design & Engineering",
    gradDateActual: "2026-12-05",
    gradDateExpected: "2026-12-05",
    gender: "Male",
    age: 30,
    locationType: "Urban",
    refugeeStatus: "Kenyan national",
    disability: "None reported",
    employment: {
      status: "Employed",
      employer: "Davis & Shirtliff",
      industry: "Renewable Energy",
      contractType: "Full-time",
      location: "Kitale",
      dateUpdated: "2026-06-23",
    },
    completeness: 95,
    surveyStatus: "Submitted",
    surveySubmitted: "2026-06-22",
  },
];

const RECENT_UPDATES = [
  { text: "Sarah Achieng Otieno marked Employed at M-KOPA Solar", time: "2 days ago" },
  { text: "Amina Hassan Yusuf profile completeness reached 100%", time: "3 days ago" },
  { text: "Grace Nyandeng Malual — follow-up survey reminder sent", time: "5 days ago" },
  { text: "David Kiptoo Rono marked Employed at Davis & Shirtliff", time: "1 week ago" },
  { text: "Cohort 14 roster imported (4 trainees)", time: "2 weeks ago" },
];

// Rough placement coordinates on the placeholder map (percent of frame)
const EMPLOYER_LOCATIONS = [
  { employer: "SolarNow Kenya", location: "Kakuma, Turkana County", x: 22, y: 20, trainee: "Nyibol Deng Akol" },
  { employer: "Renewvia Energy", location: "Kakuma Camp 1, Turkana County", x: 27, y: 24, trainee: "Amina Hassan Yusuf" },
  { employer: "Chantal Solar Solutions (self-employed)", location: "Kalobeyei Settlement, Turkana County", x: 18, y: 30, trainee: "Chantal Uwimana" },
  { employer: "Kenya Power (subcontract)", location: "Kalobeyei Settlement, Turkana County", x: 20, y: 34, trainee: "Jean-Claude Mugisha" },
  { employer: "M-KOPA Solar", location: "Nairobi", x: 58, y: 72, trainee: "Sarah Achieng Otieno" },
  { employer: "Davis & Shirtliff", location: "Kitale", x: 40, y: 46, trainee: "David Kiptoo Rono" },
];

function cohortLabel(cohortId) {
  const c = COHORTS.find((c) => c.id === cohortId);
  return c ? c.label : cohortId;
}
